version: '3'
services: 
  db:
    container_name: mysql-server
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=gonotes
      - MYSQL_ROOT_PASSWORD=1Q2w3e4r
      - MYSQL_USER=gonotes
      - MYSQL_PASSWORD=1Q2w3e4r    
    volumes:
      # - $GOPATH/src/github.com/alex-bezverkhniy/go-notes-api/.data/mysql:/var/lib/mysql
      - $GOPATH/src/github.com/alex-bezverkhniy/go-notes-api/mysql-init:/docker-entrypoint-initdb.d
  notes-api:
    container_name: notes-api
    build: .
    restart: always
    ports: 
        - "8080:8080"
    environment:
      - API_PORT=8080
      - API_DB_HOST=db      
    links: 
      - db
